function [ lines ] = DetectLines( img )

    [H, theta, rho] = hough(img);
    
    threshold = 20;
    peaks  = houghpeaks(H, threshold, 'threshold', threshold);

    maxLineGap = 190;
    minLineLen = 120;
    
    lines = houghlines( ...
            img, ...
            theta, ...
            rho, ...
            peaks, ...
            'FillGap', maxLineGap,  ...
            'MinLength', minLineLen ...
            );
    
end

