function [ lines ] = DetectLines( img )

    [H, theta, rho] = hough(img);
    
    threshold = 10;
    peaks  = houghpeaks(H, threshold, 'threshold', threshold);

    maxLineGap = 180;
    minLineLen = 150;
    
    lines = houghlines( ...
            img, ...
            theta, ...
            rho, ...
            peaks, ...
            'FillGap', maxLineGap,  ...
            'MinLength', minLineLen ...
            );
    
end

